# Generated by Django 4.1.3 on 2023-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="product", name="is_top_save_today", field=models.BooleanField(default=True))
    ]
