# Generated by Django 4.1.3 on 2023-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('user', '0002_alter_product_is_top_save_today')]

    operations = [
        migrations.AlterField(
            model_name='product', name='description', field=models.CharField(blank=True, max_length=250, null=True)
        )
    ]
