# Generated by Django 4.1.3 on 2023-06-26 09:28

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [('user', '0003_alter_product_description')]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='subcategories'),
        )
    ]
